irl_pc: D:\SelfStudyPackage\DeepLearning\MRI_classification\dataset
laptop_pc: "E:/Brats23 Data/Dataset/BraTS23_mapped/dataset"
colab: "/gdrive/MyDrive/BraTS2023/"
sines_pc: /drive/faizanai.rrl/datasets
dataset_folder: # specify your dataset path here if any of the above does not relate to you
version:  brats2023
type: brats # brats 
patient_id: "E:/Brats23 Data/Dataset/BraTS23_mapped/dataset/brats2023"
save_dir: paper_figs/exp1/modalities